language: python
python:
- '3.5'
sudo: required
dist: trusty
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O anaconda.sh;
- export python_version=$TRAVIS_PYTHON_VERSION
- bash anaconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda config --add channels http://conda.binstar.org/omnia
- bash scripts/install_datamined_conda.sh datamined
- source activate datamined
- pip install yapf==0.17.0
- pip install coveralls
- python setup.py install
- sudo apt-get install libssl-dev
- pip install py-solc
- python -m solc.install v0.4.17
script:
- nosetests -a '!slow' --with-coverage --cover-package=datamined -v datamined --nologcapture
- find ./datamined | grep .py$ |xargs python -m doctest -v
- bash devtools/travis-ci/test_format_code.sh
after_success:
- echo $TRAVIS_SECURE_ENV_VARS
- coveralls
